-- /* ********** LEGACY (WITHOUT API) ********** */
-- INSERT INTO generos_series VALUES (16, 1);   --1899
-- INSERT INTO generos_series VALUES (6,  1);   --1899
-- INSERT INTO generos_series VALUES (11, 2);   --28 Moons
-- INSERT INTO generos_series VALUES (13, 2);   --28 Moons
-- INSERT INTO generos_series VALUES (11, 3);   --A Love So Beautiful
-- INSERT INTO generos_series VALUES (22, 3);   --A Love So Beautiful
-- INSERT INTO generos_series VALUES (16, 4);   --Alice in Borderland
-- INSERT INTO generos_series VALUES (6,  4);   --Alice in Borderland
-- INSERT INTO generos_series VALUES (2,  5);   --All of Us Are Dead
-- INSERT INTO generos_series VALUES (3,  5);   --All of Us Are Dead
-- INSERT INTO generos_series VALUES (6,  6);   --AlRawabi School for Girls
-- INSERT INTO generos_series VALUES (19, 6);   --AlRawabi School for Girls
-- INSERT INTO generos_series VALUES (4,  7);   --Backstreet Rookie
-- INSERT INTO generos_series VALUES (12, 7);   --Backstreet Rookie
-- INSERT INTO generos_series VALUES (4,  8);   --Bad Boys Have It Coming
-- INSERT INTO generos_series VALUES (11, 8);   --Bad Boys Have It Coming
-- INSERT INTO generos_series VALUES (2,  9);   --Betaal
-- INSERT INTO generos_series VALUES (8,  9);   --Betaal
-- INSERT INTO generos_series VALUES (2,  10);  --Black Summer
-- INSERT INTO generos_series VALUES (6,  10);  --Black Summer

-- INSERT INTO generos_series VALUES (13, 11);  --Blue Period
-- INSERT INTO generos_series VALUES (27, 11);  --Blue Period
-- INSERT INTO generos_series VALUES (11, 12);  --Boys Over Flowers
-- INSERT INTO generos_series VALUES (22, 12);  --Boys Over Flowers
-- INSERT INTO generos_series VALUES (8,  13);  --Brooklyn Nine-Nine
-- INSERT INTO generos_series VALUES (4,  13);  --Brooklyn Nine-Nine
-- INSERT INTO generos_series VALUES (4,  14);  --Business Proposal
-- INSERT INTO generos_series VALUES (12, 14);  --Business Proposal
-- INSERT INTO generos_series VALUES (4,  15);  --Clean With Passion For Now
-- INSERT INTO generos_series VALUES (12, 15);  --Clean With Passion For Now
-- INSERT INTO generos_series VALUES (11, 16);  --Crash Course in Romance
-- INSERT INTO generos_series VALUES (19, 16);  --Crash Course in Romance
-- INSERT INTO generos_series VALUES (6,  17);  --Echoes
-- INSERT INTO generos_series VALUES (24, 17);  --Echoes
-- INSERT INTO generos_series VALUES (6,  18);  --Extracurricular
-- INSERT INTO generos_series VALUES (8,  18);  --Extracurricular
-- INSERT INTO generos_series VALUES (9,  19);  --Extraordinary Attorney Woo
-- INSERT INTO generos_series VALUES (11, 19);  --Extraordinary Attorney Woo
-- INSERT INTO generos_series VALUES (12, 20);  --Extraordinary You
-- INSERT INTO generos_series VALUES (21, 20);  --Extraordinary You

-- INSERT INTO generos_series VALUES (26, 21);  --Flower Crew
-- INSERT INTO generos_series VALUES (11, 21);  --Flower Crew
-- INSERT INTO generos_series VALUES (4,  22);  --From Me To You: Kimi ni Todoke
-- INSERT INTO generos_series VALUES (11, 22);  --From Me To You: Kimi ni Todoke
-- INSERT INTO generos_series VALUES (6,  23);  --Ginny & Georgia
-- INSERT INTO generos_series VALUES (19, 23);  --Ginny & Georgia
-- INSERT INTO generos_series VALUES (14, 24);  --Good Doctor
-- INSERT INTO generos_series VALUES (19, 24);  --Good Doctor
-- INSERT INTO generos_series VALUES (6,  25);  --Hellbound
-- INSERT INTO generos_series VALUES (16, 25);  --Hellbound
-- INSERT INTO generos_series VALUES (13, 26);  --High Water
-- INSERT INTO generos_series VALUES (22, 26);  --High Water
-- INSERT INTO generos_series VALUES (5,  27);  --Hometown Cha-Cha-Cha
-- INSERT INTO generos_series VALUES (12, 27);  --Hometown Cha-Cha-Cha
-- INSERT INTO generos_series VALUES (14, 28);  --Hospital Playlist
-- INSERT INTO generos_series VALUES (19, 28);  --Hospital Playlist
-- INSERT INTO generos_series VALUES (8,  29);  --How to Sell Drugs Online (Fast)
-- INSERT INTO generos_series VALUES (22, 29);  --How to Sell Drugs Online (Fast)
-- INSERT INTO generos_series VALUES (11, 30);  --Indian Matchmaking
-- INSERT INTO generos_series VALUES (17, 30);  --Indian Matchmaking

-- INSERT INTO generos_series VALUES (17, 31);  --Inside Job
-- INSERT INTO generos_series VALUES (22, 31);  --Inside Job
-- INSERT INTO generos_series VALUES (17, 32);  --Inside the Mind of a Cat
-- INSERT INTO generos_series VALUES (22, 32);  --Inside the Mind of a Cat
-- INSERT INTO generos_series VALUES (10, 33);  --Itaewon Class
-- INSERT INTO generos_series VALUES (11, 33);  --Itaewon Class
-- INSERT INTO generos_series VALUES (11, 34);  --It's Okay to Not Be Okay
-- INSERT INTO generos_series VALUES (19, 34);  --It's Okay to Not Be Okay
-- INSERT INTO generos_series VALUES (5,  35);  --Jane The Virgin
-- INSERT INTO generos_series VALUES (11, 35);  --Jane The Virgin
-- INSERT INTO generos_series VALUES (8,  36);  --Juvenile Justice
-- INSERT INTO generos_series VALUES (9,  36);  --Juvenile Justice
-- INSERT INTO generos_series VALUES (2,  37);  --Kingdom
-- INSERT INTO generos_series VALUES (26, 37);  --Kingdom
-- INSERT INTO generos_series VALUES (2,  38);  --La Revolución
-- INSERT INTO generos_series VALUES (26, 38);  --La Revolución
-- INSERT INTO generos_series VALUES (6,  39);  --Living in Bondage
-- INSERT INTO generos_series VALUES (13, 39);  --Living in Bondage
-- INSERT INTO generos_series VALUES (11, 40);  --Love Alarm
-- INSERT INTO generos_series VALUES (16, 40);  --Love Alarm

-- INSERT INTO generos_series VALUES (11, 41);  --Love in the Moonlight
-- INSERT INTO generos_series VALUES (26, 41);  --Love in the Moonlight
-- INSERT INTO generos_series VALUES (11, 42);  --Love to Hate You
-- INSERT INTO generos_series VALUES (12, 42);  --Love to Hate You
-- INSERT INTO generos_series VALUES (11, 43);  --Lovestruck in the City
-- INSERT INTO generos_series VALUES (22, 43);  --Lovestruck in the City
-- INSERT INTO generos_series VALUES (16, 44);  --Making 1899
-- INSERT INTO generos_series VALUES (22, 44);  --Making 1899
-- INSERT INTO generos_series VALUES (5,  45);  --Meteor Garden
-- INSERT INTO generos_series VALUES (11, 45);  --Meteor Garden
-- INSERT INTO generos_series VALUES (5,  46);  --Mismatched
-- INSERT INTO generos_series VALUES (11, 46);  --Mismatched
-- INSERT INTO generos_series VALUES (12, 47);  --Mr. Queen
-- INSERT INTO generos_series VALUES (26, 47);  --Mr. Queen
-- INSERT INTO generos_series VALUES (6,  48);  --My Name
-- INSERT INTO generos_series VALUES (8,  48);  --My Name
-- INSERT INTO generos_series VALUES (6,  49);  --Narco-Saints
-- INSERT INTO generos_series VALUES (8,  49);  --Narco-Saints
-- INSERT INTO generos_series VALUES (4,  50);  --Never Have I Ever
-- INSERT INTO generos_series VALUES (12, 50);  --Never Have I Ever

-- INSERT INTO generos_series VALUES (4,  51);  --Next in Fashion  
-- INSERT INTO generos_series VALUES (17, 51);  --Next in Fashion  
-- INSERT INTO generos_series VALUES (13, 52);  --Off Course
-- INSERT INTO generos_series VALUES (5,  52);  --Off Course
-- INSERT INTO generos_series VALUES (9,  53);  --Oh My Venus
-- INSERT INTO generos_series VALUES (11, 53);  --Oh My Venus
-- INSERT INTO generos_series VALUES (19, 54);  --Our Beloved Summer
-- INSERT INTO generos_series VALUES (22, 54);  --Our Beloved Summer
-- INSERT INTO generos_series VALUES (1,  55);  --Phenomena 
-- INSERT INTO generos_series VALUES (24, 55);  --Phenomena 
-- INSERT INTO generos_series VALUES (6,  56);  --Ragnarok  
-- INSERT INTO generos_series VALUES (21, 56);  --Ragnarok  
-- INSERT INTO generos_series VALUES (2,  57);  --Reality Z 
-- INSERT INTO generos_series VALUES (17, 57);  --Reality Z 
-- INSERT INTO generos_series VALUES (11, 58);  --Record of Youth  
-- INSERT INTO generos_series VALUES (12, 58);  --Record of Youth  
-- INSERT INTO generos_series VALUES (26, 59);  --Reply 1988
-- INSERT INTO generos_series VALUES (11, 59);  --Reply 1988
-- INSERT INTO generos_series VALUES (11, 60);  --Revolutionary Love
-- INSERT INTO generos_series VALUES (13, 60);  --Revolutionary Love  

-- INSERT INTO generos_series VALUES (13, 61);  --Romina 
-- INSERT INTO generos_series VALUES (6,  61);  --Romina 
-- INSERT INTO generos_series VALUES (11, 62);  --Rookie Historian Goo Hae-Ryung
-- INSERT INTO generos_series VALUES (26, 62);  --Rookie Historian Goo Hae-Ryung
-- INSERT INTO generos_series VALUES (17, 63);  --Samurai Gourmet  
-- INSERT INTO generos_series VALUES (22, 63);  --Samurai Gourmet  
-- INSERT INTO generos_series VALUES (12, 64);  --School 2017
-- INSERT INTO generos_series VALUES (6,  64);  --School 2017
-- INSERT INTO generos_series VALUES (4,  65);  --Sex Education
-- INSERT INTO generos_series VALUES (11, 65);  --Sex Education
-- INSERT INTO generos_series VALUES (12, 66);  --She was pretty
-- INSERT INTO generos_series VALUES (4,  66);  --She was pretty
-- INSERT INTO generos_series VALUES (11, 67);  --She Would Never Know 
-- INSERT INTO generos_series VALUES (13, 67);  --She Would Never Know 
-- INSERT INTO generos_series VALUES (11, 68);  --Smiley 
-- INSERT INTO generos_series VALUES (19, 68);  --Smiley 
-- INSERT INTO generos_series VALUES (4,  69);  --So Not Worth It  
-- INSERT INTO generos_series VALUES (12, 69);  --So Not Worth It  
-- INSERT INTO generos_series VALUES (6,  70);  --Somebody  
-- INSERT INTO generos_series VALUES (7,  70);  --Somebody  

-- INSERT INTO generos_series VALUES (4,  71);  --Space Force
-- INSERT INTO generos_series VALUES (16, 71);  --Space Force
-- INSERT INTO generos_series VALUES (6,  72);  --Squid Game
-- INSERT INTO generos_series VALUES (16, 72);  --Squid Game
-- INSERT INTO generos_series VALUES (12, 73);  --Strong Girl Bongsoon
-- INSERT INTO generos_series VALUES (21, 73);  --Strong Girl Bongsoon
-- INSERT INTO generos_series VALUES (11, 74);  --Suspicious Partner
-- INSERT INTO generos_series VALUES (9,  74);  --Suspicious Partner
-- INSERT INTO generos_series VALUES (3,  75);  --Sweet Home
-- INSERT INTO generos_series VALUES (21, 75);  --Sweet Home
-- INSERT INTO generos_series VALUES (15, 76);  --The 100
-- INSERT INTO generos_series VALUES (16, 76);  --The 100
-- INSERT INTO generos_series VALUES (8,  77);  --The Alcasser Murders 
-- INSERT INTO generos_series VALUES (22, 77);  --The Alcasser Murders 
-- INSERT INTO generos_series VALUES (1,  78);  --The Darkness 
-- INSERT INTO generos_series VALUES (24, 78);  --The Darkness 
-- INSERT INTO generos_series VALUES (6,  79);  --The Glory 
-- INSERT INTO generos_series VALUES (19, 79);  --The Glory 
-- INSERT INTO generos_series VALUES (11, 80);  --The Guide to the Perfect Family
-- INSERT INTO generos_series VALUES (12, 80);  --The Guide to the Perfect Family

-- INSERT INTO generos_series VALUES (6,  81);  --The Guilty
-- INSERT INTO generos_series VALUES (13, 81);  --The Guilty
-- INSERT INTO generos_series VALUES (11, 82);  --The Kings Affection 
-- INSERT INTO generos_series VALUES (26, 82);  --The Kings Affection 
-- INSERT INTO generos_series VALUES (1,  83);  --The Lazarus Effect
-- INSERT INTO generos_series VALUES (6,  83);  --The Lazarus Effect
-- INSERT INTO generos_series VALUES (1,  84);  --The Mist  
-- INSERT INTO generos_series VALUES (16, 84);  --The Mist  
-- INSERT INTO generos_series VALUES (19, 85);  --The Queens Gambit
-- INSERT INTO generos_series VALUES (6,  85);  --The Queens Gambit
-- INSERT INTO generos_series VALUES (1,  86);  --The Seventh Day  
-- INSERT INTO generos_series VALUES (6,  86);  --The Seventh Day  
-- INSERT INTO generos_series VALUES (6,  87);  --The Silence
-- INSERT INTO generos_series VALUES (16, 87);  --The Silence
-- INSERT INTO generos_series VALUES (6,  88);  --The Silent Sea
-- INSERT INTO generos_series VALUES (16, 88);  --The Silent Sea
-- INSERT INTO generos_series VALUES (20, 89);  --The Sound of Magic 
-- INSERT INTO generos_series VALUES (21, 89);  --The Sound of Magic 
-- INSERT INTO generos_series VALUES (23, 90);  --The Uncanny Counter
-- INSERT INTO generos_series VALUES (21, 90);  --The Uncanny Counter

-- INSERT INTO generos_series VALUES (1,  91);  --The Unholy
-- INSERT INTO generos_series VALUES (24, 91);  --The Unholy
-- INSERT INTO generos_series VALUES (2,  92);  --The Walking Dead 
-- INSERT INTO generos_series VALUES (23, 92);  --The Walking Dead 
-- INSERT INTO generos_series VALUES (11, 93);  --The Wasteland
-- INSERT INTO generos_series VALUES (19, 93);  --The Wasteland
-- INSERT INTO generos_series VALUES (15, 94);  --The Witch 
-- INSERT INTO generos_series VALUES (24, 94);  --The Witch 
-- INSERT INTO generos_series VALUES (1,  95);  --The Woman in Black
-- INSERT INTO generos_series VALUES (6,  95);  --The Woman in Black
-- INSERT INTO generos_series VALUES (2,  96);  --To the Lake
-- INSERT INTO generos_series VALUES (6,  96);  --To the Lake
-- INSERT INTO generos_series VALUES (19, 97);  --Tomorrow  
-- INSERT INTO generos_series VALUES (24, 97);  --Tomorrow  
-- INSERT INTO generos_series VALUES (1,  98);  --Unfriended
-- INSERT INTO generos_series VALUES (6,  98);  --Unfriended
-- INSERT INTO generos_series VALUES (9,  99);  --Vincenzo  
-- INSERT INTO generos_series VALUES (19, 99);  --Vincenzo  
-- INSERT INTO generos_series VALUES (12, 100); --Weightlifting Fairy Kim Bok Joo
-- INSERT INTO generos_series VALUES (21, 100); --Weightlifting Fairy Kim Bok Joo

-- INSERT INTO generos_series VALUES (8,  101); --Where is Marta?
-- INSERT INTO generos_series VALUES (22, 101); --Where is Marta?
-- INSERT INTO generos_series VALUES (4,  102); --Welcome to Waikiki
-- INSERT INTO generos_series VALUES (11, 102); --Welcome to Waikiki
-- INSERT INTO generos_series VALUES (2,  103); --Z Nation
-- INSERT INTO generos_series VALUES (4,  103); --Z Nation
-- INSERT INTO generos_series VALUES (19, 104); --Youth of May
-- INSERT INTO generos_series VALUES (26, 104); --Youth of May
-- INSERT INTO generos_series VALUES (17, 105); --100 Humans 
-- INSERT INTO generos_series VALUES (14, 105); --100 Humans 
-- INSERT INTO generos_series VALUES (17, 106); --100 Days with Tata
-- INSERT INTO generos_series VALUES (22, 106); --100 Days with Tata
-- INSERT INTO generos_series VALUES (16, 107); --Westworld 
-- INSERT INTO generos_series VALUES (6,  107); --Westworld
-- INSERT INTO generos_series VALUES (8,  108); --11M: Terror in Madrid 
-- INSERT INTO generos_series VALUES (22, 108); --11M: Terror in Madrid 
-- INSERT INTO generos_series VALUES (1,  109); --32 Malasaña Street
-- INSERT INTO generos_series VALUES (24, 109); --32 Malasaña Street
-- INSERT INTO generos_series VALUES (1,  110); --28 Days Haunted
-- INSERT INTO generos_series VALUES (24, 110); --28 Days Haunted

-- INSERT INTO generos_series VALUES (6,  111); --Alias Grace
-- INSERT INTO generos_series VALUES (13, 111); --Alias Grace
-- INSERT INTO generos_series VALUES (4,  112); --Friends
-- INSERT INTO generos_series VALUES (11, 112); --Friends
-- INSERT INTO generos_series VALUES (6,  113); --Anatomy of a Scandal
-- INSERT INTO generos_series VALUES (10, 113); --Anatomy of a Scandal
-- INSERT INTO generos_series VALUES (12, 114); --La Extraordinaria Playlist de Zoey
-- INSERT INTO generos_series VALUES (20, 114); --La Extraordinaria Playlist de Zoey
-- INSERT INTO generos_series VALUES (6,  115); --Prodigal Son
-- INSERT INTO generos_series VALUES (8,  115); --Prodigal Son
-- INSERT INTO generos_series VALUES (13, 116); --Anne with an E 
-- INSERT INTO generos_series VALUES (26, 116); --Anne with an E 
-- INSERT INTO generos_series VALUES (11, 117); --My Holo Love
-- INSERT INTO generos_series VALUES (16, 117); --My Holo Love
-- INSERT INTO generos_series VALUES (4,  118); --Aquí no hay quien viva
-- INSERT INTO generos_series VALUES (5,  118); --Aquí no hay quien viva
-- INSERT INTO generos_series VALUES (2,  119); --Resident Evil
-- INSERT INTO generos_series VALUES (23, 119); --Resident Evil
-- INSERT INTO generos_series VALUES (15, 120); --Assassin's Creed
-- INSERT INTO generos_series VALUES (22, 120); --Assassin's Creed

-- INSERT INTO generos_series VALUES (16, 121); --Altered Carbon
-- INSERT INTO generos_series VALUES (18, 121); --Altered Carbon
-- INSERT INTO generos_series VALUES (16, 122); --The Mandalorian
-- INSERT INTO generos_series VALUES (23, 122); --The Mandalorian
-- INSERT INTO generos_series VALUES (11, 123); --Bridgerton 
-- INSERT INTO generos_series VALUES (26, 123); --Bridgerton 
-- INSERT INTO generos_series VALUES (6,  124); --Breaking Bad
-- INSERT INTO generos_series VALUES (8,  124); --Breaking Bad
-- INSERT INTO generos_series VALUES (16, 125); --Tales from the Loop
-- INSERT INTO generos_series VALUES (18, 125); --Tales from the Loop
-- INSERT INTO generos_series VALUES (16, 126); --Futurama
-- INSERT INTO generos_series VALUES (18, 126); --Futurama
-- INSERT INTO generos_series VALUES (4,  127); --Casper  
-- INSERT INTO generos_series VALUES (21, 127); --Casper  
-- INSERT INTO generos_series VALUES (15, 128); --Naruto
-- INSERT INTO generos_series VALUES (27, 128); --Naruto
-- INSERT INTO generos_series VALUES (8,  129); --Fariña
-- INSERT INTO generos_series VALUES (13, 129); --Fariña  
-- INSERT INTO generos_series VALUES (13, 130); --Haikyu!
-- INSERT INTO generos_series VALUES (27, 130); --Haikyu!

-- INSERT INTO generos_series VALUES (8,  131); --Conversations with a Killer: The John Wayne Gacy Tapes
-- INSERT INTO generos_series VALUES (22, 131); --Conversations with a Killer: The John Wayne Gacy Tapes
-- INSERT INTO generos_series VALUES (13, 132); --Control Z
-- INSERT INTO generos_series VALUES (18, 132); --Control Z
-- INSERT INTO generos_series VALUES (6,  133); --Dark
-- INSERT INTO generos_series VALUES (16, 133); --Dark
-- INSERT INTO generos_series VALUES (24, 134); --Castlevania
-- INSERT INTO generos_series VALUES (27, 134); --Castlevania
-- INSERT INTO generos_series VALUES (15, 135); --(Des)encanto
-- INSERT INTO generos_series VALUES (21, 135); --(Des)encanto
-- INSERT INTO generos_series VALUES (16, 136); --V-Wars
-- INSERT INTO generos_series VALUES (24, 136); --V-Wars 
-- INSERT INTO generos_series VALUES (2,  137); --The Last of Us  
-- INSERT INTO generos_series VALUES (6,  137); --The Last of Us  
-- INSERT INTO generos_series VALUES (21, 138); --Sweet Tooth  
-- INSERT INTO generos_series VALUES (24, 138); --Sweet Tooth  
-- INSERT INTO generos_series VALUES (8,  139); --Castle
-- INSERT INTO generos_series VALUES (13, 139); --Castle
-- INSERT INTO generos_series VALUES (8,  140); --Mentes Criminales
-- INSERT INTO generos_series VALUES (13, 140); --Mentes Criminales

-- INSERT INTO generos_series VALUES (6,  141); --The Handmaid's Tale
-- INSERT INTO generos_series VALUES (16, 141); --The Handmaid's Tale
-- INSERT INTO generos_series VALUES (8,  142); --Elite
-- INSERT INTO generos_series VALUES (13, 142); --Elite
-- INSERT INTO generos_series VALUES (18, 143); --The OA
-- INSERT INTO generos_series VALUES (16, 143); --The OA
-- INSERT INTO generos_series VALUES (4,  144); --The Simpsons
-- INSERT INTO generos_series VALUES (15, 144); --The Simpsons
-- INSERT INTO generos_series VALUES (16, 145); --Duty After School
-- INSERT INTO generos_series VALUES (24, 145); --Duty After School
-- INSERT INTO generos_series VALUES (13, 146); --Examination of Conscience
-- INSERT INTO generos_series VALUES (22, 146); --Examination of Conscience
-- INSERT INTO generos_series VALUES (4,  147); --How I Met Your Mother
-- INSERT INTO generos_series VALUES (11, 147); --How I Met Your Mother
-- INSERT INTO generos_series VALUES (17, 148); --FIFA Uncovered
-- INSERT INTO generos_series VALUES (22, 148); --FIFA Uncovered
-- INSERT INTO generos_series VALUES (4,  149); --The Big Bang Theory
-- INSERT INTO generos_series VALUES (11, 149); --The Big Bang Theory
-- INSERT INTO generos_series VALUES (16, 150); --Love, Death and Robots
-- INSERT INTO generos_series VALUES (18, 150); --Love, Death and Robots

-- INSERT INTO generos_series VALUES (5,  151); --Física o Química  
-- INSERT INTO generos_series VALUES (19, 151); --Física o Química  
-- INSERT INTO generos_series VALUES (6,  152); --Snowpiercer
-- INSERT INTO generos_series VALUES (18, 152); --Snowpiercer
-- INSERT INTO generos_series VALUES (15, 153); --Las escalofriantes aventuras de Sabrina
-- INSERT INTO generos_series VALUES (16, 153); --Las escalofriantes aventuras de Sabrina
-- INSERT INTO generos_series VALUES (15, 154); --Fate: The Winx Saga
-- INSERT INTO generos_series VALUES (16, 154); --Fate: The Winx Saga
-- INSERT INTO generos_series VALUES (6,  155); --Riverdale
-- INSERT INTO generos_series VALUES (13, 155); --Riverdale
-- INSERT INTO generos_series VALUES (11, 156); --The Vampire Diaries
-- INSERT INTO generos_series VALUES (24, 156); --The Vampire Diaries
-- INSERT INTO generos_series VALUES (11, 157); --The Originals
-- INSERT INTO generos_series VALUES (24, 157); --The Originals
-- INSERT INTO generos_series VALUES (17, 158); --Home Game
-- INSERT INTO generos_series VALUES (22, 158); --Home Game
-- INSERT INTO generos_series VALUES (25, 159); --Heirs to the Land
-- INSERT INTO generos_series VALUES (26, 159); --Heirs to the Land

-- INSERT INTO generos_series VALUES (21, 160); --Los Protegidos  
-- INSERT INTO generos_series VALUES (24, 160); --Los Protegidos  
-- INSERT INTO generos_series VALUES (6,  161); --Homeland
-- INSERT INTO generos_series VALUES (8,  161); --Homeland
-- INSERT INTO generos_series VALUES (6,  162); --How to Get Away With Murder
-- INSERT INTO generos_series VALUES (9,  162); --How to Get Away With Murder
-- INSERT INTO generos_series VALUES (4,  163); --How the Grinch Stole Christmas
-- INSERT INTO generos_series VALUES (21, 163); --How the Grinch Stole Christmas
-- INSERT INTO generos_series VALUES (16, 164); --3 %
-- INSERT INTO generos_series VALUES (23, 164); --3 %
-- INSERT INTO generos_series VALUES (14, 165); --Human: The World Within 
-- INSERT INTO generos_series VALUES (22, 165); --Human: The World Within 
-- INSERT INTO generos_series VALUES (15, 166); --Island of the Sea Wolves
-- INSERT INTO generos_series VALUES (22, 166); --Island of the Sea Wolves
-- INSERT INTO generos_series VALUES (17, 167); --Insiders
-- INSERT INTO generos_series VALUES (22, 167); --Insiders
-- INSERT INTO generos_series VALUES (13, 168); --Chicago Fire
-- INSERT INTO generos_series VALUES (23, 168); --Chicago Fire
-- INSERT INTO generos_series VALUES (8,  169); --Case Cold
-- INSERT INTO generos_series VALUES (13, 169); --Case Cold
-- INSERT INTO generos_series VALUES (6,  170); --Katla
-- INSERT INTO generos_series VALUES (21, 170); --Katla

-- INSERT INTO generos_series VALUES (8,  171); --The Punisher
-- INSERT INTO generos_series VALUES (23, 171); --The Punisher
-- INSERT INTO generos_series VALUES (15, 172); --Land of the Lost  
-- INSERT INTO generos_series VALUES (16, 172); --Land of the Lost  
-- INSERT INTO generos_series VALUES (6,  173); --La Reina del Sur  
-- INSERT INTO generos_series VALUES (8,  173); --La Reina del Sur  
-- INSERT INTO generos_series VALUES (8,  174); --Agents of S.H.I.E.L.D
-- INSERT INTO generos_series VALUES (23, 174); --Agents of S.H.I.E.L.D
-- INSERT INTO generos_series VALUES (16, 175); --Good Omens
-- INSERT INTO generos_series VALUES (21, 175); --Good Omens
-- INSERT INTO generos_series VALUES (6,  176); --Los Pacientes del Doctor García  
-- INSERT INTO generos_series VALUES (13, 176); --Los Pacientes del Doctor García  
-- INSERT INTO generos_series VALUES (13, 177); --Little Women
-- INSERT INTO generos_series VALUES (19, 177); --Little Women
-- INSERT INTO generos_series VALUES (8,  178); --Lucifer 
-- INSERT INTO generos_series VALUES (21, 178); --Lucifer 
-- INSERT INTO generos_series VALUES (9,  179); --Law & Order 
-- INSERT INTO generos_series VALUES (19, 179); --Law & Order 
-- INSERT INTO generos_series VALUES (6,  180); --Treadstone
-- INSERT INTO generos_series VALUES (23, 180); --Treadstone

-- INSERT INTO generos_series VALUES (21, 181); --Lupin
-- INSERT INTO generos_series VALUES (23, 181); --Lupin
-- INSERT INTO generos_series VALUES (6,  182); --MH370: The Plane That Disappeared
-- INSERT INTO generos_series VALUES (22, 182); --MH370: The Plane That Disappeared
-- INSERT INTO generos_series VALUES (4,  183); --Merlí
-- INSERT INTO generos_series VALUES (19, 183); --Merlí
-- INSERT INTO generos_series VALUES (11, 184); --Morocco: Love in Times of War
-- INSERT INTO generos_series VALUES (13, 184); --Morocco: Love in Times of War
-- INSERT INTO generos_series VALUES (8,  185); --Money Heist: Part 1
-- INSERT INTO generos_series VALUES (23, 185); --Money Heist: Part 1
-- INSERT INTO generos_series VALUES (13, 186); --Narcos  
-- INSERT INTO generos_series VALUES (23, 186); --Narcos  
-- INSERT INTO generos_series VALUES (15, 187); --My Octopus Teacher
-- INSERT INTO generos_series VALUES (22, 187); --My Octopus Teacher
-- INSERT INTO generos_series VALUES (13, 188); --Body of Proof
-- INSERT INTO generos_series VALUES (14, 188); --Body of Proof
-- INSERT INTO generos_series VALUES (13, 189); --Narcos: Mexico 
-- INSERT INTO generos_series VALUES (23, 189); --Narcos: Mexico 
-- INSERT INTO generos_series VALUES (2,  190); --Santa Clarita Diet
-- INSERT INTO generos_series VALUES (4,  190); --Santa Clarita Diet

-- INSERT INTO generos_series VALUES (14, 191); --Chicago Med
-- INSERT INTO generos_series VALUES (19, 191); --Chicago Med
-- INSERT INTO generos_series VALUES (8,  192); --Orange Is the New Black
-- INSERT INTO generos_series VALUES (13, 192); --Orange Is the New Black
-- INSERT INTO generos_series VALUES (15, 193); --Once Upon a Time...The Discoverers
-- INSERT INTO generos_series VALUES (27, 193); --Once Upon a Time...The Discoverers
-- INSERT INTO generos_series VALUES (15, 194); --Our Universe
-- INSERT INTO generos_series VALUES (22, 194); --Our Universe
-- INSERT INTO generos_series VALUES (8,  195); --Our Father 
-- INSERT INTO generos_series VALUES (22, 195); --Our Father 
-- INSERT INTO generos_series VALUES (19, 196); --9-1-1
-- INSERT INTO generos_series VALUES (23, 196); --9-1-1
-- INSERT INTO generos_series VALUES (19, 197); --Outlander
-- INSERT INTO generos_series VALUES (26, 197); --Outlander
-- INSERT INTO generos_series VALUES (13, 198); --Grey's Anatomy
-- INSERT INTO generos_series VALUES (14, 198); --Grey's Anatomy
-- INSERT INTO generos_series VALUES (15, 199); --Pokemon The Series: Indigo League
-- INSERT INTO generos_series VALUES (27, 199); --Pokemon The Series: Indigo League
-- INSERT INTO generos_series VALUES (11, 200); --Run On
-- INSERT INTO generos_series VALUES (12, 200); --Run On

-- INSERT INTO generos_series VALUES (6,  201); --The Terminal List
-- INSERT INTO generos_series VALUES (23, 201); --The Terminal List
-- INSERT INTO generos_series VALUES (6,  202); --Safe House
-- INSERT INTO generos_series VALUES (13, 202); --Safe House
-- INSERT INTO generos_series VALUES (6,  203); --The Night Agent
-- INSERT INTO generos_series VALUES (23, 203); --The Night Agent
-- INSERT INTO generos_series VALUES (13, 204); --Scorpion
-- INSERT INTO generos_series VALUES (23, 204); --Scorpion
-- INSERT INTO generos_series VALUES (8,  205); --S.W.A.T
-- INSERT INTO generos_series VALUES (23, 205); --S.W.A.T
-- INSERT INTO generos_series VALUES (21, 206); --Shadow and Bone
-- INSERT INTO generos_series VALUES (24, 206); --Shadow and Bone
-- INSERT INTO generos_series VALUES (15, 207); --The Book of Boba Fett
-- INSERT INTO generos_series VALUES (23, 207); --The Book of Boba Fett
-- INSERT INTO generos_series VALUES (16, 208); --Andor
-- INSERT INTO generos_series VALUES (23, 208); --Andor
-- INSERT INTO generos_series VALUES (6,  209); --Sherlock
-- INSERT INTO generos_series VALUES (8,  209); --Sherlock
-- INSERT INTO generos_series VALUES (16, 210); --The Expanse
-- INSERT INTO generos_series VALUES (21, 210); --The Expanse

-- INSERT INTO generos_series VALUES (21, 211); --Doraemon
-- INSERT INTO generos_series VALUES (27, 211); --Doraemon
-- INSERT INTO generos_series VALUES (15, 212); --Spirited Away
-- INSERT INTO generos_series VALUES (27, 212); --Spirited Away
-- INSERT INTO generos_series VALUES (6,  213); --Stranger Things
-- INSERT INTO generos_series VALUES (16, 213); --Stranger Things
-- INSERT INTO generos_series VALUES (23, 214); --Dragon Ball Z
-- INSERT INTO generos_series VALUES (27, 214); --Dragon Ball Z
-- INSERT INTO generos_series VALUES (2,  215); --Fear The Walking Dead
-- INSERT INTO generos_series VALUES (3,  215); --Fear The Walking Dead
-- INSERT INTO generos_series VALUES (1,  216); --Surviving Death
-- INSERT INTO generos_series VALUES (22, 216); --Surviving Death
-- INSERT INTO generos_series VALUES (9,  217); --Suits
-- INSERT INTO generos_series VALUES (13, 217); --Suits
-- INSERT INTO generos_series VALUES (13, 218); --The Barrier
-- INSERT INTO generos_series VALUES (16, 218); --The Barrier
-- INSERT INTO generos_series VALUES (13, 219); --House
-- INSERT INTO generos_series VALUES (14, 219); --House
-- INSERT INTO generos_series VALUES (6,  220); --The Boat
-- INSERT INTO generos_series VALUES (15, 220); --The Boat

-- INSERT INTO generos_series VALUES (8,  221); --The Blacklist
-- INSERT INTO generos_series VALUES (23, 221); --The Blacklist
-- INSERT INTO generos_series VALUES (4,  222); --True Beauty
-- INSERT INTO generos_series VALUES (12, 222); --True Beauty
-- INSERT INTO generos_series VALUES (13, 223); --The Bonfire of Destiny
-- INSERT INTO generos_series VALUES (26, 223); --The Bonfire of Destiny
-- INSERT INTO generos_series VALUES (11, 224); --My Roommate is a Gumiho
-- INSERT INTO generos_series VALUES (24, 224); --My Roommate is a Gumiho
-- INSERT INTO generos_series VALUES (2,  225); --Happiness
-- INSERT INTO generos_series VALUES (6,  225); --Happiness
-- INSERT INTO generos_series VALUES (22, 226); --The Crow
-- INSERT INTO generos_series VALUES (26, 226); --The Crow
-- INSERT INTO generos_series VALUES (11, 227); --The Cook of Castamar
-- INSERT INTO generos_series VALUES (26, 227); --The Cook of Castamar
-- INSERT INTO generos_series VALUES (23, 228); --Descendants of the Sun
-- INSERT INTO generos_series VALUES (25, 228); --Descendants of the Sun
-- INSERT INTO generos_series VALUES (21, 229); --Abyss
-- INSERT INTO generos_series VALUES (24, 229); --Abyss
-- INSERT INTO generos_series VALUES (4,  230); --The Flintstones
-- INSERT INTO generos_series VALUES (27, 230); --The Flintstones

-- INSERT INTO generos_series VALUES (22, 231); --The Figo Affair: The Transfer that Changed Football 
-- INSERT INTO generos_series VALUES (23, 231); --The Figo Affair: The Transfer that Changed Football 
-- INSERT INTO generos_series VALUES (6,  232); --La Brea 
-- INSERT INTO generos_series VALUES (16, 232); --La Brea 
-- INSERT INTO generos_series VALUES (13, 233); --Euphoria
-- INSERT INTO generos_series VALUES (19, 233); --Euphoria
-- INSERT INTO generos_series VALUES (6,  234); --The Outsider
-- INSERT INTO generos_series VALUES (24, 234); --The Outsider
-- INSERT INTO generos_series VALUES (15, 235); --Primal
-- INSERT INTO generos_series VALUES (23, 235); --Primal
-- INSERT INTO generos_series VALUES (8,  236); --Killing Eve
-- INSERT INTO generos_series VALUES (23, 236); --Killing Eve
-- INSERT INTO generos_series VALUES (6,  237); --True Detective
-- INSERT INTO generos_series VALUES (8,  237); --True Detective
-- INSERT INTO generos_series VALUES (6,  238); --The Leftlovers
-- INSERT INTO generos_series VALUES (21, 238); --The Leftlovers
-- INSERT INTO generos_series VALUES (8,  239); --Quantico
-- INSERT INTO generos_series VALUES (23, 239); --Quantico
-- INSERT INTO generos_series VALUES (6,  240); --The Minions of Midas
-- INSERT INTO generos_series VALUES (13, 240); --The Minions of Midas

-- INSERT INTO generos_series VALUES (6,  241); --The Head
-- INSERT INTO generos_series VALUES (7,  241); --The Head
-- INSERT INTO generos_series VALUES (8,  242); --The Raincoat Killer
-- INSERT INTO generos_series VALUES (22, 242); --The Raincoat Killer
-- INSERT INTO generos_series VALUES (8,  243); --Lie To Me
-- INSERT INTO generos_series VALUES (13, 243); --Lie To Me
-- INSERT INTO generos_series VALUES (10, 244); --Scandal
-- INSERT INTO generos_series VALUES (13, 244); --Scandal
-- INSERT INTO generos_series VALUES (11, 245); --Soundtrack #1
-- INSERT INTO generos_series VALUES (20, 245); --Soundtrack #1
-- INSERT INTO generos_series VALUES (11, 246); --Rookie Cops
-- INSERT INTO generos_series VALUES (8,  246); --Rookie Cops
-- INSERT INTO generos_series VALUES (6,  247); --Only Murders in the Building
-- INSERT INTO generos_series VALUES (7,  247); --Only Murders in the Building
-- INSERT INTO generos_series VALUES (11, 248); --Un Paso Adelante
-- INSERT INTO generos_series VALUES (20, 248); --Un Paso Adelante
-- INSERT INTO generos_series VALUES (1,  249); --American Horror Story
-- INSERT INTO generos_series VALUES (24, 249); --American Horror Story
-- INSERT INTO generos_series VALUES (8,  250); --Vatican Girl: The Disappearance of Emanuela Orlandi
-- INSERT INTO generos_series VALUES (22, 250); --Vatican Girl: The Disappearance of Emanuela Orlandi

-- INSERT INTO generos_series VALUES (6,  251); --Unsolved Mysteries
-- INSERT INTO generos_series VALUES (8,  251); --Unsolved Mysteries
-- INSERT INTO generos_series VALUES (11, 252); --Virgin River
-- INSERT INTO generos_series VALUES (13, 252); --Virgin River
-- INSERT INTO generos_series VALUES (25, 253); --Vikings
-- INSERT INTO generos_series VALUES (26, 253); --Vikings
-- INSERT INTO generos_series VALUES (1,  254); --Wednesday
-- INSERT INTO generos_series VALUES (21, 254); --Wednesday
-- INSERT INTO generos_series VALUES (6,  255); --You
-- INSERT INTO generos_series VALUES (7,  255); --You
-- INSERT INTO generos_series VALUES (6,  256); --Wrong Side of the Tracks
-- INSERT INTO generos_series VALUES (11, 256); --Wrong Side of the Tracks